/**
 * Hono environment for the PokeMystery Worker.
 *
 * `Env` itself is generated by `wrangler types` into worker-configuration.d.ts
 * from wrangler.jsonc, so bindings stay in sync with configuration.
 */
export interface AppEnv {
  // `wrangler types` narrows string vars to their literal configured values;
  // widen the toggles so runtime overrides (.dev.vars, dashboard) typecheck.
  Bindings: Omit<Env, 'AI_PARSER_ENABLED' | 'AI_PARSER_MODEL'> & {
    AI_PARSER_ENABLED: string;
    AI_PARSER_MODEL: string | undefined;
    /** Present only when the optional `ai` binding is enabled in wrangler.jsonc. */
    AI?: Ai;
  };
}
