/**
 * Hono environment for the PokeMystery Worker.
 *
 * `Env` itself is generated by `wrangler types` into worker-configuration.d.ts
 * from wrangler.jsonc, so bindings stay in sync with configuration.
 */
export interface AppEnv {
  Bindings: Env;
}
